### ISSUE TITLE
(snap) jhack reads juju status as empty

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [PietroPasotti/jhack#30]
Output from `jhack tail`:
```
Traceback (most recent call last):
  File "/snap/jhack/124/bin/jhack", line 8, in <module>
    sys.exit(main())
  File "/snap/jhack/124/lib/python3.8/site-packages/jhack/main.py", line 138, in main
    app()
  File "/snap/jhack/124/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/snap/jhack/124/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/snap/jhack/124/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/snap/jhack/124/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/snap/jhack/124/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/jhack/124/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/snap/jhack/124/lib/python3.8/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/snap/jhack/124/lib/python3.8/site-packages/jhack/utils/tail_charms.py", line 919, in tail_events
    return _tail_events(
  File "/snap/jhack/124/lib/python3.8/site-packages/jhack/utils/tail_charms.py", line 974, in _tail_events
    targets = parse_targets(targets) if not files else (targets or [])
  File "/snap/jhack/124/lib/python3.8/site-packages/jhack/utils/tail_charms.py", line 105, in parse_targets
    return get_all_units()
  File "/snap/jhack/124/lib/python3.8/site-packages/jhack/utils/tail_charms.py", line 98, in get_all_units
    chain(*(app.get("units", ()) for app in status["applications"].values()))
KeyError: 'applications'
```

I used `pdb.set_trace()` [here](https://github.com/PietroPasotti/jhack/blob/46e3501ccd10b6dd0a29a4bf6038e3537e8d93e3/jhack/utils/tail_charms.py#L97) to check the values of: ([by following this method](https://askubuntu.com/a/1036611))
`juju_status(json=True)` was `{}`
`jhack.helpers.juju_version()` was `'3.0.0'`
`jhack.helpers.juju_models()` was `''`

In my local environment:
`juju version` was `2.9.37-ubuntu-amd64`
Copy-pasting code from `tail_charms.py` into a python3 interpreter gave me:
`raw` was `'2.9.37-ubuntu-amd64'`
`raw.split("-")[0]` was `'2.9.37'`

I did run this command: `sudo snap connect jhack:dot-local-share-juju snapd`

I also tried refreshing the snap from `latest/stable:    0.3.2 2022-11-02 (120)` to `latest/beta:      0.3.2 2022-11-22 (124)` and `latest/edge:      0.3.2 2022-11-24 (126)` with the same issue.

Running on Google Compute Engine Ubuntu 22.04
<details>
<summary>GCE environment:</summary>

```json
{
  "creationTimestamp": "2022-11-28T10:47:13.287-08:00",
  "description": "",
  "id": "3183457864939781342",
  "kind": "compute#instanceTemplate",
  "name": "dev-env",
  "properties": {
    "confidentialInstanceConfig": {
      "enableConfidentialCompute": false
    },
    "description": "",
    "scheduling": {
      "onHostMaintenance": "MIGRATE",
      "provisioningModel": "STANDARD",
      "automaticRestart": true,
      "instanceTerminationAction": "STOP",
      "maxRunDuration": {
        "seconds": "36000",
        "nanos": 0
      },
      "preemptible": false
    },
    "tags": {},
    "disks": [
      {
        "type": "PERSISTENT",
        "deviceName": "instance-template-1",
        "autoDelete": true,
        "index": 0,
        "boot": true,
        "kind": "compute#attachedDisk",
        "mode": "READ_WRITE",
        "initializeParams": {
          "sourceImage": "projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20221123",
          "diskType": "pd-ssd",
          "diskSizeGb": "50"
        }
      }
    ],
    "networkInterfaces": [
      {
        "stackType": "IPV4_ONLY",
        "name": "nic0",
        "network": "projects/dev-env-369519/global/networks/default",
        "accessConfigs": [
          {
            "name": "External NAT",
            "type": "ONE_TO_ONE_NAT",
            "kind": "compute#accessConfig",
            "networkTier": "PREMIUM"
          }
        ],
        "kind": "compute#networkInterface"
      }
    ],
    "reservationAffinity": {
      "consumeReservationType": "ANY_RESERVATION"
    },
    "canIpForward": false,
    "keyRevocationActionType": "NONE",
    "machineType": "n2-standard-4",
    "metadata": {
      "fingerprint": "rhj2YiywKp4=",
      "kind": "compute#metadata",
      "items": [
        {
          "value": "#cloud-config\npackage_upgrade: true\npackages:\n  - gnome-keyring\n  - tox\nsnap:\n  commands:\n    - snap refresh\n    - snap install juju --classic --channel=2.9/stable\n    - snap install charmcraft --classic\n    - snap install lxd\n    - snap install microk8s --classic\n    - snap alias microk8s.kubectl kubectl\n    - snap install jhack\n    - snap connect jhack:dot-local-share-juju snapd\nruncmd:\n  - adduser ubuntu lxd\n  - newgrp lxd\n  - lxd init --auto\n  - lxc network set lxdbr0 ipv6.address none\n  - adduser ubuntu microk8s\n  - newgrp microk8s\n  - microk8s status --wait-ready\n  - microk8s enable dns\n  - kubectl rollout status -n kube-system -w --timeout=5m deployments/coredns\n  - microk8s enable hostpath-storage\n  - kubectl rollout status -n kube-system -w --timeout=5m deployments/hostpath-provisioner\n",
          "key": "user-data"
        },
        {
          "value": "ubuntu:ssh-ed25519 [redacted] ubuntu",
          "key": "ssh-keys"
        }
      ]
    },
    "shieldedVmConfig": {
      "enableSecureBoot": false,
      "enableVtpm": true,
      "enableIntegrityMonitoring": true
    },
    "shieldedInstanceConfig": {
      "enableSecureBoot": false,
      "enableVtpm": true,
      "enableIntegrityMonitoring": true
    },
    "displayDevice": {
      "enableDisplay": false
    }
  },
  "selfLink": "projects/dev-env-369519/global/instanceTemplates/dev-env"
}
```
</details>

<details>
<summary>Cloud-init:</summary>

```yaml
#cloud-config
package_upgrade: true
packages:
  - gnome-keyring
  - tox
snap:
  commands:
    - snap refresh
    - snap install juju --classic --channel=2.9/stable
    - snap install charmcraft --classic
    - snap install lxd
    - snap install microk8s --classic
    - snap alias microk8s.kubectl kubectl
    - snap install jhack
    - snap connect jhack:dot-local-share-juju snapd
runcmd:
  - adduser ubuntu lxd
  - newgrp lxd
  - lxd init --auto
  - lxc network set lxdbr0 ipv6.address none
  - adduser ubuntu microk8s
  - newgrp microk8s
  - microk8s status --wait-ready
  - microk8s enable dns
  - kubectl rollout status -n kube-system -w --timeout=5m deployments/coredns
  - microk8s enable hostpath-storage
  - kubectl rollout status -n kube-system -w --timeout=5m deployments/hostpath-provisioner

```
</details>

<details>
<summary>Commands run as `ubuntu` user after cloud-init:</summary>

```
juju bootstrap microk8s micro --agent-version=2.9.29
juju bootstrap localhost lxd --agent-version=2.9.29
juju model-defaults logging-config='<root>=INFO; unit=DEBUG'
ssh-keygen -t ed25519
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_ed25519
cat ~/.ssh/id_ed25519.pub
juju switch micro

# something along the lines of
juju add-model foo
```
</details>
